[package]
name = "ohai_cargo"
version = "0.1.0"
authors = ["Ryan Morrison-Westphal <ryan@trippingthebits.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
